/**
 * The word bank.
 *
 * A pair is [civilian word, undercover word, level]; level 1 is far apart,
 * 2 is close. Custom pairs come in at level 0.
 *
 * WHAT MAKES A PAIR GOOD. This is the whole game, so it is worth stating:
 * a pair works when you can think of a clue that fits both words AND a clue
 * that tells them apart. Two failures to watch for:
 *
 *   - Too close: one word is a kind of the other, or they share a word, so
 *     every clue fits both and the undercover can never be caught. Hond/Puppy
 *     and Golf/Minigolf fail this way. `words.test.ts` catches the mechanical
 *     cases; the rest is judgement.
 *   - Too far: no clue fits both, so the undercover is out in round one.
 *     Pizza/Fiets fails this way.
 *
 * Pairs are written per language, not translated. Dutch gets frikandel and
 * Sinterklaas because that is what a Dutch table knows; a translated list
 * feels Dutch in every language.
 */
import type { Locale } from "./i18n/config.ts";

export type Pair = [string, string, number];

export type CategoryId =
  | "eten"
  | "dieren"
  | "plekken"
  | "huis"
  | "beroepen"
  | "sport"
  | "pop";

/** The custom-words bucket is a category too, so it can be switched off. */
export type BucketId = CategoryId | "eigen";

/** The word language is the app language; there is only one. */
export type LangId = Locale;

export const CATEGORY_IDS: CategoryId[] = [
  "eten",
  "dieren",
  "plekken",
  "huis",
  "beroepen",
  "sport",
  "pop",
];

/** Minimum a verified language has to carry before it goes in the picker. */
export const MIN_VERIFIED_PAIRS = 150;

export const WORDS: Record<LangId, Record<CategoryId, Pair[]>> = {
  nl: {
    eten: [
      ["Pizza", "Hamburger", 1],
      ["Appel", "Banaan", 1],
      ["Koffie", "Thee", 1],
      ["Friet", "Chips", 1],
      ["Kaas", "Boter", 1],
      ["Sushi", "Kapsalon", 1],
      ["Soep", "Stamppot", 1],
      ["Patat", "Kibbeling", 1],
      ["Stroopwafel", "Speculaas", 2],
      ["Pannenkoek", "Poffertjes", 2],
      ["Hagelslag", "Muisjes", 2],
      ["Bitterbal", "Kroket", 2],
      ["Brood", "Beschuit", 2],
      ["Roomijs", "Milkshake", 2],
      ["Pindakaas", "Chocopasta", 2],
      ["Druif", "Rozijn", 2],
      ["Erwtensoep", "Goulash", 2],
      ["Drop", "Winegum", 2],
      ["Boerenkool", "Zuurkool", 2],
      ["Oliebol", "Donut", 2],
      ["Mosterd", "Mayonaise", 2],
      ["Haring", "Makreel", 2],
    ],
    dieren: [
      ["Kat", "Hond", 1],
      ["Haai", "Dolfijn", 1],
      ["Uil", "Papegaai", 1],
      ["Pinguïn", "IJsbeer", 1],
      ["Mier", "Bij", 1],
      ["Leeuw", "Tijger", 2],
      ["Paard", "Ezel", 2],
      ["Kikker", "Pad", 2],
      ["Muis", "Rat", 2],
      ["Koe", "Geit", 2],
      ["Schaap", "Lama", 2],
      ["Krokodil", "Hagedis", 2],
      ["Olifant", "Neushoorn", 2],
      ["Zeehond", "Otter", 2],
      ["Vlinder", "Mot", 2],
      ["Kraai", "Ekster", 2],
      ["Konijn", "Haas", 2],
      ["Octopus", "Inktvis", 2],
      ["Wolf", "Vos", 2],
      ["Kameel", "Dromedaris", 2],
      ["Kanarie", "Parkiet", 2],
      ["Egel", "Stekelvarken", 2],
    ],
    plekken: [
      ["Strand", "Zwembad", 1],
      ["Ziekenhuis", "Apotheek", 1],
      ["Vliegveld", "Treinstation", 1],
      ["Camping", "Hotel", 1],
      ["Woestijn", "Oerwoud", 1],
      ["Zolder", "Kelder", 1],
      ["Dierentuin", "Circus", 1],
      ["Bioscoop", "Theater", 2],
      ["Bibliotheek", "Boekwinkel", 2],
      ["Supermarkt", "Warenhuis", 2],
      ["Kasteel", "Paleis", 2],
      ["Kerk", "Moskee", 2],
      ["Museum", "Galerie", 2],
      ["Sportschool", "Sauna", 2],
      ["Berg", "Heuvel", 2],
      ["Snackbar", "Restaurant", 2],
      ["Nagelstudio", "Zonnebank", 2],
      ["Tankstation", "Garage", 2],
      ["Brandweerkazerne", "Politiebureau", 2],
      ["Gevangenis", "Rechtbank", 2],
      ["Pretpark", "Kermis", 2],
      ["Haven", "Werf", 2],
    ],
    huis: [
      ["Kaars", "Lamp", 1],
      ["Bank", "Bed", 1],
      ["Tandenborstel", "Kam", 1],
      ["Paraplu", "Regenjas", 1],
      ["Bezem", "Stofzuiger", 1],
      ["Spiegel", "Raam", 2],
      ["Koelkast", "Vriezer", 2],
      ["Kussen", "Deken", 2],
      ["Wekker", "Horloge", 2],
      ["Stoel", "Kruk", 2],
      ["Pan", "Wok", 2],
      ["Mes", "Schaar", 2],
      ["Handdoek", "Washandje", 2],
      ["Gordijn", "Rolluik", 2],
      ["Trap", "Ladder", 2],
      ["Sleutel", "Slot", 2],
      ["Vaas", "Pot", 2],
      ["Deurbel", "Deurmat", 2],
      ["Schilderij", "Poster", 2],
      ["Zeep", "Shampoo", 2],
      ["Emmer", "Teil", 2],
      ["Kachel", "Radiator", 2],
    ],
    beroepen: [
      ["Politie", "Brandweer", 1],
      ["Boer", "Tuinman", 1],
      ["Journalist", "Fotograaf", 1],
      ["Acteur", "Zanger", 1],
      ["Astronaut", "Duiker", 1],
      ["Dokter", "Tandarts", 2],
      ["Kok", "Bakker", 2],
      ["Piloot", "Kapitein", 2],
      ["Leraar", "Directeur", 2],
      ["Detective", "Spion", 2],
      ["Kapper", "Visagist", 2],
      ["Schilder", "Stukadoor", 2],
      ["Advocaat", "Notaris", 2],
      ["Loodgieter", "Elektricien", 2],
      ["Dierenarts", "Verpleger", 2],
      ["Buschauffeur", "Treinmachinist", 2],
      ["Postbode", "Koerier", 2],
      ["Monteur", "Timmerman", 2],
      ["Slager", "Visboer", 2],
      ["Architect", "Aannemer", 2],
      ["Barman", "Ober", 2],
      ["Bibliothecaris", "Archivaris", 2],
    ],
    sport: [
      ["Voetbal", "Hockey", 1],
      ["Boksen", "Judo", 1],
      ["Darts", "Bowlen", 1],
      ["Fietsen", "Hardlopen", 1],
      ["Paardrijden", "Wielrennen", 1],
      ["Dansen", "Schermen", 1],
      ["Tennis", "Padel", 2],
      ["Schaken", "Dammen", 2],
      ["Zwemmen", "Duiken", 2],
      ["Skiën", "Snowboarden", 2],
      ["Basketbal", "Volleybal", 2],
      ["Turnen", "Ballet", 2],
      ["Golf", "Jeu de boules", 2],
      ["Roeien", "Kanoën", 2],
      ["Schaatsen", "Skeeleren", 2],
      ["Handbal", "Korfbal", 2],
      ["Yoga", "Pilates", 2],
      ["Marathon", "Triatlon", 2],
      ["Zeilen", "Surfen", 2],
      ["Biljart", "Poolen", 2],
      ["Honkbal", "Cricket", 2],
      ["Klimmen", "Abseilen", 2],
    ],
    pop: [
      ["Batman", "Spider-Man", 1],
      ["Harry Potter", "Gandalf", 1],
      ["Mario", "Sonic", 1],
      ["Netflix", "YouTube", 1],
      ["Shrek", "Hulk", 1],
      ["Spotify", "Radio", 1],
      ["TikTok", "Instagram", 2],
      ["Pikachu", "Hello Kitty", 2],
      ["Frozen", "Moana", 2],
      ["Darth Vader", "Voldemort", 2],
      ["Minecraft", "Roblox", 2],
      ["Disney", "Pixar", 2],
      ["Lego", "Playmobil", 2],
      ["WhatsApp", "Snapchat", 2],
      ["Pokémon", "Digimon", 2],
      ["Marvel", "DC", 2],
      ["Donald Duck", "Mickey Mouse", 2],
      ["Fortnite", "Call of Duty", 2],
      ["James Bond", "Jason Bourne", 2],
      ["Sinterklaas", "Kerstman", 2],
      ["PlayStation", "Xbox", 2],
      ["Emoji", "Sticker", 2],
    ],
  },

  en: {
    eten: [
      ["Pizza", "Burger", 1],
      ["Coffee", "Tea", 1],
      ["Apple", "Banana", 1],
      ["Cheese", "Butter", 1],
      ["Fries", "Crisps", 1],
      ["Sushi", "Ramen", 1],
      ["Pancake", "Waffle", 2],
      ["Donut", "Bagel", 2],
      ["Soup", "Stew", 2],
      ["Ice cream", "Milkshake", 2],
      ["Bread", "Toast", 2],
      ["Grape", "Raisin", 2],
      ["Ketchup", "Mustard", 2],
      ["Pasta", "Noodles", 2],
      ["Chocolate", "Caramel", 2],
      ["Pie", "Tart", 2],
      ["Bacon", "Sausage", 2],
      ["Lemonade", "Iced tea", 2],
      ["Popcorn", "Pretzel", 2],
      ["Salmon", "Tuna", 2],
      ["Cereal", "Porridge", 2],
      ["Honey", "Syrup", 2],
    ],
    dieren: [
      ["Cat", "Dog", 1],
      ["Shark", "Dolphin", 1],
      ["Owl", "Parrot", 1],
      ["Penguin", "Polar bear", 1],
      ["Ant", "Bee", 1],
      ["Lion", "Tiger", 2],
      ["Frog", "Toad", 2],
      ["Horse", "Donkey", 2],
      ["Mouse", "Rat", 2],
      ["Cow", "Goat", 2],
      ["Crocodile", "Lizard", 2],
      ["Elephant", "Rhino", 2],
      ["Seal", "Otter", 2],
      ["Butterfly", "Moth", 2],
      ["Crow", "Magpie", 2],
      ["Rabbit", "Hare", 2],
      ["Octopus", "Squid", 2],
      ["Wolf", "Fox", 2],
      ["Camel", "Llama", 2],
      ["Hedgehog", "Porcupine", 2],
      ["Eagle", "Hawk", 2],
      ["Whale", "Manatee", 2],
    ],
    plekken: [
      ["Beach", "Pool", 1],
      ["Airport", "Harbour", 1],
      ["Hospital", "Pharmacy", 1],
      ["Campsite", "Hotel", 1],
      ["Desert", "Jungle", 1],
      ["Attic", "Basement", 1],
      ["Zoo", "Circus", 1],
      ["Cinema", "Theatre", 2],
      ["Castle", "Palace", 2],
      ["Library", "Bookshop", 2],
      ["Supermarket", "Corner shop", 2],
      ["Church", "Mosque", 2],
      ["Museum", "Gallery", 2],
      ["Gym", "Sauna", 2],
      ["Mountain", "Hill", 2],
      ["Diner", "Restaurant", 2],
      ["Barbershop", "Nail salon", 2],
      ["Garage", "Workshop", 2],
      ["Fire engine", "Police car", 2],
      ["Prison", "Courthouse", 2],
      ["Theme park", "Funfair", 2],
      ["Lighthouse", "Windmill", 2],
    ],
    huis: [
      ["Candle", "Lamp", 1],
      ["Sofa", "Bed", 1],
      ["Toothbrush", "Comb", 1],
      ["Umbrella", "Raincoat", 1],
      ["Broom", "Hoover", 1],
      ["Mirror", "Window", 2],
      ["Fridge", "Freezer", 2],
      ["Pillow", "Blanket", 2],
      ["Alarm clock", "Watch", 2],
      ["Chair", "Stool", 2],
      ["Pan", "Wok", 2],
      ["Knife", "Scissors", 2],
      ["Towel", "Flannel", 2],
      ["Curtain", "Blind", 2],
      ["Stairs", "Ladder", 2],
      ["Key", "Lock", 2],
      ["Vase", "Pot", 2],
      ["Doorbell", "Doormat", 2],
      ["Painting", "Poster", 2],
      ["Soap", "Shampoo", 2],
      ["Bucket", "Basin", 2],
      ["Heater", "Radiator", 2],
    ],
    beroepen: [
      ["Police", "Firefighter", 1],
      ["Farmer", "Gardener", 1],
      ["Journalist", "Photographer", 1],
      ["Actor", "Singer", 1],
      ["Astronaut", "Diver", 1],
      ["Doctor", "Dentist", 2],
      ["Pilot", "Captain", 2],
      ["Detective", "Spy", 2],
      ["Chef", "Baker", 2],
      ["Teacher", "Principal", 2],
      ["Barber", "Stylist", 2],
      ["Painter", "Plasterer", 2],
      ["Lawyer", "Notary", 2],
      ["Plumber", "Electrician", 2],
      ["Vet", "Nurse", 2],
      ["Taxi driver", "Tour guide", 2],
      ["Postman", "Courier", 2],
      ["Mechanic", "Carpenter", 2],
      ["Butcher", "Fishmonger", 2],
      ["Architect", "Builder", 2],
      ["Bartender", "Waiter", 2],
      ["Librarian", "Archivist", 2],
    ],
    sport: [
      ["Football", "Hockey", 1],
      ["Boxing", "Judo", 1],
      ["Darts", "Bowling", 1],
      ["Cycling", "Running", 1],
      ["Horse riding", "Motor racing", 1],
      ["Dancing", "Fencing", 1],
      ["Tennis", "Padel", 2],
      ["Chess", "Checkers", 2],
      ["Swimming", "Diving", 2],
      ["Skiing", "Snowboarding", 2],
      ["Basketball", "Volleyball", 2],
      ["Gymnastics", "Ballet", 2],
      ["Golf", "Croquet", 2],
      ["Rowing", "Canoeing", 2],
      ["Ice skating", "Rollerblading", 2],
      ["Handball", "Netball", 2],
      ["Yoga", "Pilates", 2],
      ["Marathon", "Triathlon", 2],
      ["Sailing", "Surfing", 2],
      ["Snooker", "Billiards", 2],
      ["Baseball", "Cricket", 2],
      ["Climbing", "Abseiling", 2],
    ],
    pop: [
      ["Batman", "Spider-Man", 1],
      ["Mario", "Sonic", 1],
      ["Harry Potter", "Gandalf", 1],
      ["Netflix", "YouTube", 1],
      ["Shrek", "Hulk", 1],
      ["Spotify", "Radio", 1],
      ["TikTok", "Instagram", 2],
      ["Frozen", "Moana", 2],
      ["Pikachu", "Hello Kitty", 2],
      ["Darth Vader", "Voldemort", 2],
      ["Minecraft", "Roblox", 2],
      ["Disney", "Pixar", 2],
      ["Lego", "Playmobil", 2],
      ["WhatsApp", "Snapchat", 2],
      ["Pokémon", "Digimon", 2],
      ["Marvel", "DC", 2],
      ["Donald Duck", "Mickey Mouse", 2],
      ["Fortnite", "Call of Duty", 2],
      ["James Bond", "Jason Bourne", 2],
      ["Santa", "Easter Bunny", 2],
      ["PlayStation", "Xbox", 2],
      ["Emoji", "Sticker", 2],
    ],
  },

  // --- Not yet read through by a native speaker ----------------------------
  // These stay out of the picker until somebody has gone over them. See
  // VERIFIED_LANGS above.

  de: {
    eten: [["Pizza", "Hamburger", 1], ["Kaffee", "Tee", 1], ["Brezel", "Brötchen", 2], ["Wurst", "Schnitzel", 2]],
    dieren: [["Katze", "Hund", 1], ["Hai", "Delfin", 1], ["Löwe", "Tiger", 2], ["Frosch", "Kröte", 2]],
    plekken: [["Strand", "Schwimmbad", 1], ["Flughafen", "Bahnhof", 1], ["Kino", "Theater", 2], ["Burg", "Palast", 2]],
    huis: [["Kerze", "Lampe", 1], ["Sofa", "Bett", 1], ["Spiegel", "Fenster", 2], ["Kissen", "Decke", 2]],
    beroepen: [["Polizist", "Feuerwehrmann", 1], ["Arzt", "Apotheker", 2], ["Koch", "Bäcker", 2], ["Detektiv", "Spion", 2]],
    sport: [["Fußball", "Hockey", 1], ["Boxen", "Judo", 1], ["Tennis", "Padel", 2], ["Schach", "Dame", 2]],
    pop: [["Batman", "Spider-Man", 1], ["Mario", "Sonic", 1], ["TikTok", "Instagram", 2], ["Frozen", "Moana", 2]],
  },
  fr: {
    eten: [["Pizza", "Hamburger", 1], ["Café", "Thé", 1], ["Croissant", "Baguette", 2], ["Crêpe", "Gaufre", 2]],
    dieren: [["Chat", "Chien", 1], ["Requin", "Dauphin", 1], ["Lion", "Tigre", 2], ["Grenouille", "Crapaud", 2]],
    plekken: [["Plage", "Piscine", 1], ["Aéroport", "Gare", 1], ["Cinéma", "Théâtre", 2], ["Château", "Palais", 2]],
    huis: [["Bougie", "Lampe", 1], ["Canapé", "Lit", 1], ["Miroir", "Fenêtre", 2], ["Oreiller", "Couverture", 2]],
    beroepen: [["Policier", "Pompier", 1], ["Médecin", "Dentiste", 2], ["Cuisinier", "Boulanger", 2], ["Détective", "Espion", 2]],
    sport: [["Football", "Hockey", 1], ["Boxe", "Judo", 1], ["Tennis", "Padel", 2], ["Échecs", "Dames", 2]],
    pop: [["Batman", "Spider-Man", 1], ["Mario", "Sonic", 1], ["Astérix", "Tintin", 2], ["Frozen", "Moana", 2]],
  },
  es: {
    eten: [["Pizza", "Hamburguesa", 1], ["Café", "Té", 1], ["Paella", "Risotto", 2], ["Churros", "Donuts", 2]],
    dieren: [["Gato", "Perro", 1], ["Tiburón", "Delfín", 1], ["León", "Tigre", 2], ["Rana", "Sapo", 2]],
    plekken: [["Playa", "Piscina", 1], ["Aeropuerto", "Estación", 1], ["Cine", "Teatro", 2], ["Castillo", "Palacio", 2]],
    huis: [["Vela", "Lámpara", 1], ["Sofá", "Cama", 1], ["Espejo", "Ventana", 2], ["Almohada", "Manta", 2]],
    beroepen: [["Policía", "Bombero", 1], ["Médico", "Dentista", 2], ["Cocinero", "Panadero", 2], ["Detective", "Espía", 2]],
    sport: [["Fútbol", "Hockey", 1], ["Boxeo", "Judo", 1], ["Tenis", "Pádel", 2], ["Ajedrez", "Damas", 2]],
    pop: [["Batman", "Spider-Man", 1], ["Mario", "Sonic", 1], ["TikTok", "Instagram", 2], ["Frozen", "Moana", 2]],
  },
  it: {
    eten: [["Pizza", "Lasagne", 1], ["Caffè", "Tè", 1], ["Gelato", "Sorbetto", 2], ["Spaghetti", "Tagliatelle", 2]],
    dieren: [["Gatto", "Cane", 1], ["Squalo", "Delfino", 1], ["Leone", "Tigre", 2], ["Rana", "Rospo", 2]],
    plekken: [["Spiaggia", "Piscina", 1], ["Aeroporto", "Stazione", 1], ["Cinema", "Teatro", 2], ["Castello", "Palazzo", 2]],
    huis: [["Candela", "Lampada", 1], ["Divano", "Letto", 1], ["Specchio", "Finestra", 2], ["Cuscino", "Coperta", 2]],
    beroepen: [["Poliziotto", "Pompiere", 1], ["Medico", "Dentista", 2], ["Cuoco", "Fornaio", 2], ["Detective", "Spia", 2]],
    sport: [["Calcio", "Hockey", 1], ["Boxe", "Judo", 1], ["Tennis", "Padel", 2], ["Scacchi", "Dama", 2]],
    pop: [["Batman", "Spider-Man", 1], ["Mario", "Sonic", 1], ["TikTok", "Instagram", 2], ["Frozen", "Moana", 2]],
  },
  tr: {
    eten: [["Pizza", "Hamburger", 1], ["Kahve", "Çay", 1], ["Baklava", "Lokum", 2], ["Döner", "Lahmacun", 2]],
    dieren: [["Kedi", "Köpek", 1], ["Köpekbalığı", "Yunus", 1], ["Aslan", "Kaplan", 2], ["Kurbağa", "Kaplumbağa", 2]],
    plekken: [["Plaj", "Havuz", 1], ["Havalimanı", "Tren garı", 1], ["Sinema", "Tiyatro", 2], ["Kale", "Saray", 2]],
    huis: [["Mum", "Lamba", 1], ["Kanepe", "Yatak", 1], ["Ayna", "Pencere", 2], ["Yastık", "Battaniye", 2]],
    beroepen: [["Polis", "İtfaiyeci", 1], ["Doktor", "Diş hekimi", 2], ["Aşçı", "Fırıncı", 2], ["Dedektif", "Casus", 2]],
    sport: [["Futbol", "Hokey", 1], ["Boks", "Judo", 1], ["Tenis", "Padel", 2], ["Satranç", "Dama", 2]],
    pop: [["Batman", "Spider-Man", 1], ["Mario", "Sonic", 1], ["TikTok", "Instagram", 2], ["Frozen", "Moana", 2]],
  },
};

/** Stand-in names for anyone who leaves their field blank. */
export const ALIASES = [
  "Sherlock","Poirot","Columbo","Marple","Baantjer","Maigret","Watson","Clouseau",
  "Gadget","Holmes","Morse","Kojak","Magnum","Bond","Tintin","Lupin","Fletcher",
  "Nancy","Scooby","Fox",
];

export function pairCount(lang: LangId, id: CategoryId): number {
  return WORDS[lang][id].length;
}

export function totalPairs(lang: LangId): number {
  return CATEGORY_IDS.reduce((sum, id) => sum + pairCount(lang, id), 0);
}
